[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "never"


[[services]]
name = "frontend"
source = "2-react-migrated-version/frontend"
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s build -p $PORT"

[services.variables]
REACT_APP_API_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}/api/v1"
